ignored:
  - DL3003 # warning: Use WORKDIR to switch to a directory
  - DL3008 # warning: Pin versions in apt get install.
  - DL3042 # warning: Avoid cache directory with pip install --no-cache-dir <package>
