[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = 'scan-to-paperless'
version = '0.0.0'
description = 'Not used'
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "1.22.4"
scipy = "1.8.1"
scikit-image = "0.19.2"
opencv-python-headless = "4.5.5.64"
deskew = "1.0.19"
jsonschema-gentypes = "1.0.0"
"ruamel.yaml" = "0.17.21"

[tool.poetry.dev-dependencies]
prospector = {version = "1.7.7", extras = ["with_bandit", "with_mypy", "with_pyroma"]}
pytest = "7.1.2"
coverage = "6.3.0"
pytest-profiling = "1.7.0"
pyroma = "3.3"
