checks:
  versions: False
  required_workflows:
    backport.yaml: False
    audit.yaml: False
    main.yaml: False

publish:
  docker:
    images:
      - name: sbrunner/scan-to-paperless
        group: docker
        tags:
          - '{version}'
          - '{version}-all'
    repository:
      github:
        versions: []
